### ISSUE TITLE
开启giscus和gitalk碰到的一点问题

### ISSUE THREAD

**Issue by abba01001** [ch1ny/kira-hexo#36]
giscus.ejs里    <script src="<%- theme.cdn.giscus.js %>" 这里debug报错读不到。
换成    <script src="https://giscus.app/client.js" 成功解决
不知道什么原理，找了好久才解决的

**Comment by ch1ny** [comment]
是不是 `_config.kira.yml` 里没有进行相关配置呢？

```yaml
cdn:
    gitalk:
        css: https://unpkg.com/gitalk@latest/dist/gitalk.css
        js: https://unpkg.com/gitalk@latest/dist/gitalk.min.js
    giscus:
        js: https://giscus.app/client.js
```

![image](https://github.com/ch1ny/kira-hexo/assets/57794772/c944aa74-134b-4f59-944d-84464956f405)
